/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dogwalker;

import java.util.ArrayList;

/**
 *
 * @author kulksoh21
 */
public class CreateAccount extends javax.swing.JPanel
{
    private ArrayList<person> listOfUsernames = new ArrayList<>();
    private ArrayList<person> listOfPasswords = new ArrayList<>();
    private static int userIndex = 0; 
    private static int passwordIndex = 0; 
    public CreateAccount()
    {
        initComponents();
        userIndex++;
        passwordIndex++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        newUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        confirmNewPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(240, 240, 240));

        newUsername.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newUsernameActionPerformed(evt);
            }
        });

        jLabel1.setText("Create Your Account!");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        newPassword.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newPasswordActionPerformed(evt);
            }
        });

        jLabel4.setText("Confirm Password:");

        confirmNewPassword.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                confirmNewPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confirmNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(newPassword)
                            .addComponent(newUsername))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newUsernameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newUsernameActionPerformed
    {//GEN-HEADEREND:event_newUsernameActionPerformed
        // TODO add your handling code here:
        person p = new person();
        String usr = newUsername.getText();
        p.setUsername(usr);
        listOfUsernames.add(p);
    }//GEN-LAST:event_newUsernameActionPerformed

    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newPasswordActionPerformed
    {//GEN-HEADEREND:event_newPasswordActionPerformed
        // TODO add your handling code here:
         person p = new person();
        String pswd = newPassword.getText();
        p.setPassword(pswd);
        listOfPasswords.add(p);
    }//GEN-LAST:event_newPasswordActionPerformed

    private void confirmNewPasswordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_confirmNewPasswordActionPerformed
    {//GEN-HEADEREND:event_confirmNewPasswordActionPerformed
        // TODO add your handling code here:
        person p = new person();
        String pswd = confirmNewPassword.getText();
        p = listOfPasswords.get(passwordIndex);

    }//GEN-LAST:event_confirmNewPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmNewPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField newPassword;
    private javax.swing.JTextField newUsername;
    // End of variables declaration//GEN-END:variables
}
