/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dogwalker;



import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JComboBox;
import javax.swing.SwingUtilities;

/**
 *
 * @author kulksoh21
 */
public class LoggedInScreen extends javax.swing.JPanel
{

    /**
     * Creates new form LoggedIN
     */
    private static double distanceLeft = 0;
    private static double foodLeft = 0;
    public LoggedInScreen()
    {
        initComponents();
        jLabel2.setVisible(false);
        ErrorMessage.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        Distance = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        Weight = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ErrorMessage = new java.awt.Label();

        setBackground(new java.awt.Color(255, 204, 204));

        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("What has your dog done today?");

        Distance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MI", "KM" }));
        Distance.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                DistanceMouseClicked(evt);
            }
        });
        Distance.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DistanceActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane2);

        Weight.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KG", "LB" }));
        Weight.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                WeightActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("PLEASE ENTER THE VALUES");

        ErrorMessage.setText("label1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Distance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Distance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Weight))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int maximumKMWalked = -1;
        int maximumMIWalked = 0;
        int maximumKGEaten = -2;
        int maximumLBSEaten = 1;
        ParentFrame j = (ParentFrame) SwingUtilities.getWindowAncestor(this);
        ErrorMessage.setText("");
        String s = jTextPane1.getText();
        String r = jTextPane2.getText();
        if (s.isEmpty() || r.isEmpty())
        {
            jLabel2.setVisible(true);
        } else
        {        
        Scanner sc2 = new Scanner(r);
            if (Weight.getSelectedItem().equals("KG"))
            {
                if (sc2.hasNextDouble())
            {
                foodLeft = sc2.nextDouble();
                if (4.83 - foodLeft <= 0)
                {
                   foodLeft = maximumKGEaten;
                } else{
                foodLeft = 4.83 - foodLeft;
                }
            }else{
                ErrorMessage.setText("ERROR, enter a number!");
            }
            }else
        {
            if (sc2.hasNextDouble())
            {
                foodLeft = sc2.nextDouble();
                if (1 - foodLeft <= 0)
                {
                    foodLeft = maximumLBSEaten;
                }else{
                foodLeft = 1 - foodLeft;
                }
            } else
            {
                ErrorMessage.setText("ERROR, enter a number!");
            }
        }
            if (ErrorMessage.getText().equals("ERROR, enter a number!"))
            {
            
            }else{
                j.showPanel(2);
            }
        Scanner sc = new Scanner(s);
        if (Distance.getSelectedItem().equals("KM"))
        {
            if (sc.hasNextDouble())
            {
                distanceLeft = sc.nextDouble();
                if (4.83 - distanceLeft <= 0)
                {
                    distanceLeft = maximumKMWalked;
                } else{
                distanceLeft = 4.83 - distanceLeft;
                }
            }else{
                ErrorMessage.setText("ERROR, enter a number!");
            } 
        } else
        {
            if (sc.hasNextDouble())
            {
                distanceLeft = sc.nextDouble();
                if (3-distanceLeft <= 0)
                {
                    distanceLeft = maximumMIWalked;
                }else{
                distanceLeft = 3 - distanceLeft;
                }
            } else
            {
                ErrorMessage.setText("ERROR, enter a number!");
            }
        }
            if (ErrorMessage.getText().equals("ERROR, enter a number!"))
            {
            
            }else{
                j.showPanel(2);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed
        public double getDistanceLeft(){
            return distanceLeft;
        }
        public double getAmountLeft(){
            return foodLeft;
        }
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton1MouseClicked
    {//GEN-HEADEREND:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void DistanceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DistanceActionPerformed
    {//GEN-HEADEREND:event_DistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanceActionPerformed

    private void DistanceMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_DistanceMouseClicked
    {//GEN-HEADEREND:event_DistanceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanceMouseClicked

    private void WeightActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_WeightActionPerformed
    {//GEN-HEADEREND:event_WeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Distance;
    private java.awt.Label ErrorMessage;
    private javax.swing.JComboBox Weight;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
