/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dogwalker;

import javax.swing.SwingUtilities;

/**
 *
 * @author kulksoh21
 */
public class StatisticsScreen extends javax.swing.JPanel
{

    /**
     * Creates new form StatisticsScreen
     */
    public StatisticsScreen()
    {
        initComponents();
        resultText.setVisible(false);
        resultText2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        resultText = new javax.swing.JLabel();
        resultText2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setText("Click here to get your results!");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        resultText.setText("jLabel1");

        resultText2.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultText)
                    .addComponent(resultText2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(resultText)
                .addGap(18, 18, 18)
                .addComponent(resultText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton1MouseClicked
    {//GEN-HEADEREND:event_jButton1MouseClicked
        // TODO add your handling code here:
        LoggedInScreen s = new LoggedInScreen();
        double dist = s.getDistanceLeft();
        resultText.setVisible(true);
        resultText2.setVisible(true);
        if (dist == -1)
        {
            resultText.setText("You do not need to walk anymore though it would not hurt to still play with it!");
        } else
        {
            resultText.setText("You need to walk " + dist + " km more!");
        }
        if (dist == 0)
        {
            resultText.setText("You do not need to walk any more though it would not hurt to still play with it!");
        } else
        {
            resultText.setText("You need to walk " + dist + " mi more!");
        }
        double foodLeft = s.getAmountLeft();
                if (foodLeft == -2)
        {
            resultText2.setText("You do not need to give more food!");
        } else
        {
            resultText2.setText("You need to give " + foodLeft + " kg more food!");
        }
        if (foodLeft == 1)
        {
            resultText2.setText("You do not need to give more food!");
        } else
        {
            resultText2.setText("You need to give " + foodLeft + " lbs more food!");
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ParentFrame j = (ParentFrame) SwingUtilities.getWindowAncestor(this);
        j.showPanel(1);
        resultText.setVisible(false);
        resultText2.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel resultText;
    private javax.swing.JLabel resultText2;
    // End of variables declaration//GEN-END:variables
}
